require('init-packer')
require('init-lsp')
require('init-basic')
require('init-treesitter')
require('init-keybindings')
require('init-tokyonight')
-- require('init-vscode')
require('init-lualine')
require('init-tree')
require('init-buffer')
require('init-dashbord')
require('init-toggleterm')
require('init-lspinstall')
require('lsp/init-mason')
require('lsp/init-dap')
require('lsp/init-dapui')
require('lsp/init-cc++')
require('lsp/lua')
require('lsp/init-html')
-- vim.cmd[[colorscheme tokyonight]]

